module.exports = [
    {
        name: "Two Jack Lakeside Campground",
        town: "Banff, AB",
        description:
            "A beautiful campsite located next to the pristine Two Jack Lake in Banff National Park.",
        price: 30,
        longitude: -115.5273,
        latitude: 51.205,
    },
    {
        name: "Whistlers Campground",
        town: "Jasper, AB",
        description:
            "The largest campground in Jasper National Park, offering stunning mountain views.",
        price: 28,
        longitude: -118.0719,
        latitude: 52.8863,
    },
    {
        name: "Green Point Campground",
        town: "Tofino, BC",
        description:
            "Situated on a forested terrace above Long Beach in Pacific Rim National Park Reserve.",
        price: 35,
        longitude: -125.7543,
        latitude: 49.0525,
    },
    {
        name: "Cypress Hills Campground",
        town: "Maple Creek, SK",
        description: "Located in Cypress Hills Interprovincial Park with diverse flora and fauna.",
        price: 25,
        longitude: -109.9315,
        latitude: 49.6584,
    },
    {
        name: "Gros Morne Campground",
        town: "Rocky Harbour, NL",
        description:
            "Located in Gros Morne National Park, known for its striking landscapes and geological features.",
        price: 30,
        longitude: -57.8323,
        latitude: 49.5615,
    },
    {
        name: "Algonquin Park Mew Lake Campground",
        town: "Algonquin Park, ON",
        description:
            "A year-round campsite in Algonquin Provincial Park, ideal for hiking and canoeing.",
        price: 40,
        longitude: -78.3803,
        latitude: 45.5351,
    },
    {
        name: "Kouchibouguac National Park Campground",
        town: "Kouchibouguac, NB",
        description: "Features beautiful sandy beaches and lush forests.",
        price: 35,
        longitude: -64.9501,
        latitude: 46.8177,
    },
    {
        name: "Cape Breton Highlands Campground",
        town: "Ingonish Beach, NS",
        description: "Offers breathtaking coastal views and access to the famous Cabot Trail.",
        price: 30,
        longitude: -60.402,
        latitude: 46.641,
    },
    {
        name: "Fundy National Park Campground",
        town: "Alma, NB",
        description: "Located near the world's highest tides in the Bay of Fundy.",
        price: 30,
        longitude: -64.946,
        latitude: 45.5936,
    },
    {
        name: "Prince Edward Island National Park Campground",
        town: "Cavendish, PE",
        description: "Features red sand beaches and rich cultural history.",
        price: 35,
        longitude: -63.3894,
        latitude: 46.4901,
    },
    {
        name: "Yoho National Park Campground",
        town: "Field, BC",
        description: "Home to stunning waterfalls and scenic hiking trails.",
        price: 28,
        longitude: -116.4823,
        latitude: 51.4986,
    },
    {
        name: "Thousand Islands National Park Campground",
        town: "Mallorytown, ON",
        description: "Offers island camping in the beautiful Thousand Islands region.",
        price: 35,
        longitude: -75.8773,
        latitude: 44.378,
    },
    {
        name: "Riding Mountain National Park Campground",
        town: "Wasagaming, MB",
        description: "Located in a diverse ecosystem of prairies, forests, and lakes.",
        price: 30,
        longitude: -99.9484,
        latitude: 50.6612,
    },
    {
        name: "Wapusk National Park Campground",
        town: "Churchill, MB",
        description: "Known for polar bear and beluga whale sightings.",
        price: 25,
        longitude: -94.065,
        latitude: 58.615,
    },
    {
        name: "Waterton Lakes National Park Campground",
        town: "Waterton Park, AB",
        description: "Offers stunning mountain views and abundant wildlife.",
        price: 35,
        longitude: -113.912,
        latitude: 49.0502,
    },
    {
        name: "Point Pelee National Park Campground",
        town: "Leamington, ON",
        description: "Famous for bird watching and butterfly migrations.",
        price: 25,
        longitude: -82.5163,
        latitude: 41.9632,
    },
    {
        name: "Kejimkujik National Park Campground",
        town: "Maitland Bridge, NS",
        description: "Offers backcountry camping and Mi'kmaw cultural heritage.",
        price: 30,
        longitude: -65.2183,
        latitude: 44.4052,
    },
    {
        name: "La Mauricie National Park Campground",
        town: "Saint-Jean-des-Piles, QC",
        description: "Located in the Laurentian mountains with numerous lakes and trails.",
        price: 35,
        longitude: -72.9143,
        latitude: 46.7331,
    },
    {
        name: "Kluane National Park Campground",
        town: "Haines Junction, YT",
        description: "Known for its glaciers and hiking opportunities.",
        price: 25,
        longitude: -138.5721,
        latitude: 60.7556,
    },
    {
        name: "Nahanni National Park Reserve Campground",
        town: "Fort Simpson, NT",
        description: "Features the stunning Virginia Falls and rugged wilderness.",
        price: 30,
        longitude: -124.9198,
        latitude: 61.9522,
    },
    {
        name: "Auyuittuq National Park Campground",
        town: "Pangnirtung, NU",
        description: "Known for its dramatic fjords and glaciers.",
        price: 30,
        longitude: -65.3571,
        latitude: 66.1451,
    },
    {
        name: "Wood Buffalo National Park Campground",
        town: "Fort Smith, NT",
        description:
            "Largest national park in Canada, home to bison and the Peace-Athabasca Delta.",
        price: 20,
        longitude: -112.234,
        latitude: 59.3956,
    },
    {
        name: "Terra Nova National Park Campground",
        town: "Glovertown, NL",
        description: "Offers scenic coastal landscapes and forested areas.",
        price: 30,
        longitude: -53.9532,
        latitude: 48.622,
    },
    {
        name: "Forillon National Park Campground",
        town: "Gaspé, QC",
        description: "Features dramatic cliffs and diverse marine life.",
        price: 28,
        longitude: -64.2111,
        latitude: 48.8532,
    },
    {
        name: "Georgian Bay Islands National Park Campground",
        town: "Honey Harbour, ON",
        description: "Comprised of 63 small islands in Georgian Bay.",
        price: 35,
        longitude: -79.8641,
        latitude: 44.9,
    },
    {
        name: "Pukaskwa National Park Campground",
        town: "Heron Bay, ON",
        description: "Offers stunning views of Lake Superior's rugged coastline.",
        price: 30,
        longitude: -86.5294,
        latitude: 48.469,
    },
    {
        name: "Prince Albert National Park Campground",
        town: "Waskesiu Lake, SK",
        description: "Known for its boreal forest and abundant wildlife.",
        price: 25,
        longitude: -106.0795,
        latitude: 53.9226,
    },
    {
        name: "Elk Island National Park Campground",
        town: "Fort Saskatchewan, AB",
        description: "Home to free-roaming bison and diverse bird species.",
        price: 30,
        longitude: -112.8451,
        latitude: 53.5972,
    },
];
